name: Automated tests

on:
  push: ~
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2


      - name: Run tests
        run: |
          pip install tox
          tox

      - name: Code coverage upload
        uses: codecov/codecov-action@v1
